{% set name = "pydub" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed3bbb49a1ca4858d4bd153b3c0e2f2ce523d2aa054b5f17c6f9df01ab6e5051

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pydub

about:
  home: http://pydub.com
  license: MIT
  license_family: MIT
  # License file not included in PyPI package
  # license_file: LICENSE
  summary: Manipulate audio with a simple and easy high level interface
  doc_url: http://pydub.com
  dev_url: https://github.com/jiaaro/pydub

extra:
  recipe-maintainers:
    - kynan
