{% set name = "pydub" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3fb5f3c60c4eb4af84666342507e8983f3a96b87b6ef90e13b996d4402942e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pydub

about:
  home: http://pydub.com
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Manipulate audio with a simple and easy high level interface
  doc_url: http://pydub.com
  dev_url: https://github.com/jiaaro/pydub

extra:
  recipe-maintainers:
    - kynan
    - owenlamont
