travis:
  secure:
    BINSTAR_TOKEN: fSkwRY32meuVJgkS9XiJHrUXpLloiP2O3jQC0tR02rFDp+Jh11qq/X3/reMV5JMIlv6oVuBQBJrWe/LKbitSRYnWG5RXwMttveIv+PUrBQ+IYrE9M39aS58bdHyx4/8RSOOaUR/RZyBH3M6o9FojrJ+qqMTTRkI/dz2VToGia8scN3db4Tb4Le0sW+Dpm0rO/wsQ5kXkoVA7mYd0YQHmJUBKg9HbKRyfwcUooOK0Hk5cER3Q4sOKi+o0H5PRgl2Nx5nkEry/+D+YPKZP1xb+PDh7eguJZ3r88OEuTYQK6QdpIB3qGmviDywYZg7Mu7Y25hOkri8+f33bT9NrQ6G6mG1haRGkfViQrOGeHqTx3dFC/4T5aYaylkxudcjLasAR0HAowfmsRWnLHviGEHmWjfTICJsDhiESB6V8Xh12QPSpe5uapEscyp+5tseOzbJFQ/il44T9TFFKlvmxsAgG/iAyEJC04AEMhMOYyha/S8nrYP8h0E8/X/F5p/U96RbeRAwztgfpuZJHaJV/20T1JYFzYRNm/sb9bSrZsi3eQ1278cSS82bAZ8gY/5XpdQFyTU5ZB/Tesifj3FLCRCO+G1KZ3GZi4wSRhxcpa0gNpcboBSZBw614tIF3YthWgCwpXz4+WZxvTEkMuqpXSBZ2IQlIbYHqbCSyKn3NrssUXH0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
